import { StudentDashboardModule } from '../models/student-dashboard-module.model';

const MODULE_ASSET_ROOT = '/assets/student/dashboard/modules';

export const STUDENT_DASHBOARD_MODULES: readonly StudentDashboardModule[] = [
  {
    id: 'academics',
    label: 'Academics',
    imagePath: `${MODULE_ASSET_ROOT}/academics.webp`,
    route: '/student/academics',
    ariaLabel: 'Open academics',
    background: 'var(--student-module-academics)',
    enabled: false,
    order: 1,
    imageWidth: 384,
    imageHeight: 384,
  },
  {
    id: 'attendance',
    label: 'Attendance',
    imagePath: `${MODULE_ASSET_ROOT}/attendance.webp`,
    route: '/student/attendance',
    ariaLabel: 'Open attendance',
    background: 'var(--student-module-attendance)',
    enabled: false,
    order: 2,
    imageWidth: 384,
    imageHeight: 384,
  },
  {
    id: 'fees',
    label: 'Fees',
    imagePath: `${MODULE_ASSET_ROOT}/fees.webp`,
    route: '/student/fees',
    ariaLabel: 'Open fees',
    background: 'var(--student-module-fees)',
    enabled: false,
    order: 3,
    imageWidth: 384,
    imageHeight: 384,
  },
  {
    id: 'exams',
    label: 'Exams',
    imagePath: `${MODULE_ASSET_ROOT}/exams.webp`,
    route: '/student/exams',
    ariaLabel: 'Open exams',
    background: 'var(--student-module-exams)',
    enabled: false,
    order: 4,
    imageWidth: 384,
    imageHeight: 384,
  },
  {
    id: 'hostel',
    label: 'Hostel',
    imagePath: `${MODULE_ASSET_ROOT}/hostel.webp`,
    route: '/student/hostel',
    ariaLabel: 'Open hostel',
    background: 'var(--student-module-hostel)',
    enabled: false,
    order: 5,
    imageWidth: 384,
    imageHeight: 384,
  },
  {
    id: 'complaints',
    label: 'Complaints',
    imagePath: `${MODULE_ASSET_ROOT}/complaints.webp`,
    route: '/student/complaints',
    ariaLabel: 'Open complaints',
    background: 'var(--student-module-complaints)',
    enabled: false,
    order: 6,
    imageWidth: 384,
    imageHeight: 384,
  },
  {
    id: 'placement',
    label: 'Placement',
    imagePath: `${MODULE_ASSET_ROOT}/placement.webp`,
    route: '/student/placement',
    ariaLabel: 'Open placement',
    background: 'var(--student-module-placement)',
    enabled: false,
    order: 7,
    imageWidth: 384,
    imageHeight: 384,
  },
  {
    id: 'documents',
    label: 'Documents',
    imagePath: `${MODULE_ASSET_ROOT}/documents.webp`,
    route: '/student/documents',
    ariaLabel: 'Open documents',
    background: 'var(--student-module-documents)',
    enabled: false,
    order: 8,
    imageWidth: 384,
    imageHeight: 384,
  },
  {
    id: 'campus',
    label: 'Campus',
    imagePath: `${MODULE_ASSET_ROOT}/campus.webp`,
    route: '/student/campus',
    ariaLabel: 'Open campus',
    background: 'var(--student-module-campus)',
    enabled: false,
    order: 9,
    imageWidth: 384,
    imageHeight: 384,
  },
].sort((left, right) => left.order - right.order);
