import { StudentNavigationItem } from '../models/student-navigation.model';
import {
  LucideBriefcaseBusiness,
  LucideBuilding2,
  LucideCalendarCheck,
  LucideClipboardCheck,
  LucideFolderOpen,
  LucideGraduationCap,
  LucideLayoutDashboard,
  LucideMessagesSquare,
  LucideSchool,
  LucideWalletCards,
} from '@lucide/angular';

const STUDENT_NAVIGATION_ICONS = {
  'layout-dashboard': LucideLayoutDashboard,
  'graduation-cap': LucideGraduationCap,
  'calendar-check': LucideCalendarCheck,
  'wallet-cards': LucideWalletCards,
  'clipboard-check': LucideClipboardCheck,
  'building-2': LucideBuilding2,
  'messages-square': LucideMessagesSquare,
  'briefcase-business': LucideBriefcaseBusiness,
  'folder-open': LucideFolderOpen,
  school: LucideSchool,
} as const;

export function studentNavigationIcon(icon: string) {
  return STUDENT_NAVIGATION_ICONS[icon as keyof typeof STUDENT_NAVIGATION_ICONS];
}

export const STUDENT_NAVIGATION: readonly StudentNavigationItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: 'layout-dashboard',
    route: '/student/dashboard',
    ariaLabel: 'Open student dashboard',
    enabled: true,
    order: 1,
  },
  {
    id: 'academics',
    label: 'Academics',
    icon: 'graduation-cap',
    route: '/student/academics',
    ariaLabel: 'Open academics',
    enabled: false,
    order: 2,
  },
  {
    id: 'attendance',
    label: 'Attendance',
    icon: 'calendar-check',
    route: '/student/attendance',
    ariaLabel: 'Open attendance',
    enabled: false,
    order: 3,
  },
  {
    id: 'fees',
    label: 'Fees',
    icon: 'wallet-cards',
    route: '/student/fees',
    ariaLabel: 'Open fees',
    enabled: true,
    order: 4,
  },
  {
    id: 'exams',
    label: 'Exams',
    icon: 'clipboard-check',
    route: '/student/exams',
    ariaLabel: 'Open exams',
    enabled: false,
    order: 5,
  },
  {
    id: 'hostel',
    label: 'Hostel',
    icon: 'building-2',
    route: '/student/hostel',
    ariaLabel: 'Open hostel',
    enabled: false,
    order: 6,
  },
  {
    id: 'complaints',
    label: 'Complaints',
    icon: 'messages-square',
    route: '/student/complaints',
    ariaLabel: 'Open complaints',
    enabled: false,
    order: 7,
  },
  {
    id: 'placement',
    label: 'Placement',
    icon: 'briefcase-business',
    route: '/student/placement',
    ariaLabel: 'Open placement',
    enabled: false,
    order: 8,
  },
  {
    id: 'documents',
    label: 'Documents',
    icon: 'folder-open',
    route: '/student/documents',
    ariaLabel: 'Open documents',
    enabled: false,
    order: 9,
  },
  {
    id: 'campus',
    label: 'Campus',
    icon: 'school',
    route: '/student/campus',
    ariaLabel: 'Open campus',
    enabled: false,
    order: 10,
  },
].sort((left, right) => left.order - right.order);
